name: .NET

on:
  push:
    tags:
    - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Set Build Variables
      env:
        REF_TYPE: ${{ github.ref_type }}
        REF_NAME: ${{ github.ref_name }}
        RUN_NUMBER: ${{ github.run_number }}
      run: |
        if ($env:REF_TYPE -eq 'tag') {
          $version = $env:REF_NAME.Substring(1)
          $artifactSuffix = $env:REF_NAME
        } else {
          $version = "0.0.$env:RUN_NUMBER.0"
          $artifactSuffix = "run-$env:RUN_NUMBER"
        }

        "VERSION=$version" >> $env:GITHUB_ENV
        "ARTIFACT_SUFFIX=$artifactSuffix" >> $env:GITHUB_ENV
    - name: Build for Windows
      run: |
        dotnet publish UnrealAssetScout/UnrealAssetScout.csproj -c Debug --runtime win-x64 -o ./artifacts/win-x64-framework-dependent -p:PublishSingleFile=true -p:SelfContained=false -p:Version=$env:VERSION -p:AssemblyVersion=$env:VERSION
        dotnet publish UnrealAssetScout/UnrealAssetScout.csproj -c Debug --runtime win-x64 -o ./artifacts/win-x64-self-contained -p:PublishSingleFile=true -p:SelfContained=true -p:Version=$env:VERSION -p:AssemblyVersion=$env:VERSION
    - name: Create Windows archives
      run: |
        Compress-Archive -Path ./artifacts/win-x64-framework-dependent/* -DestinationPath ./UnrealAssetScout-$env:ARTIFACT_SUFFIX.zip -Force
        Compress-Archive -Path ./artifacts/win-x64-self-contained/* -DestinationPath ./UnrealAssetScout-$env:ARTIFACT_SUFFIX-self-contained.zip -Force
    - name: Generate release notes
      if: ${{ github.ref_type == 'tag' }}
      env:
        REPOSITORY: ${{ github.repository }}
        SERVER_URL: ${{ github.server_url }}
        REF_NAME: ${{ github.ref_name }}
      run: |
        ./Build/Get-ReleaseNotes.ps1 -ChangelogPath ./CHANGELOG.md -Tag $env:REF_NAME -OutputPath ./release-notes.md -Repository $env:REPOSITORY -ServerUrl $env:SERVER_URL
    - name: Upload framework-dependent artifact
      uses: actions/upload-artifact@v6
      with:
        name: UnrealAssetScout-${{ env.ARTIFACT_SUFFIX }}
        path: ./artifacts/win-x64-framework-dependent/*
    - name: Upload self-contained artifact
      uses: actions/upload-artifact@v6
      with:
        name: UnrealAssetScout-${{ env.ARTIFACT_SUFFIX }}-self-contained
        path: ./artifacts/win-x64-self-contained/*
    - name: Create Release
      if: ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v2
      with:
        body_path: ./release-notes.md
        files: |
          UnrealAssetScout-${{ env.ARTIFACT_SUFFIX }}.zip
          UnrealAssetScout-${{ env.ARTIFACT_SUFFIX }}-self-contained.zip
